# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'style_venv_for_currency_liver.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(22, 22, 34);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Widgets = QtWidgets.QTabWidget(self.centralwidget)
        self.Widgets.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Widgets.setFont(font)
        self.Widgets.setStyleSheet("/* VERTICAL SCROLEBAR */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(55, 110, 190);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:rgb(34, 34, 53);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(55, 110, 190);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color:rgb(34, 34, 53);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color:rgb(55, 110, 190);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* TABWIDGETS */\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid rgb(80, 80, 122);\n"
"    border-bottom: 2px solid rgb(80, 80, 122);\n"
"    border-left: 2px solid rgb(80, 80, 122);\n"
"    border-right: 2px solid rgb(80, 80, 122)\n"
"\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0  rgb(80, 80, 122), stop: 0.4  rgb(80, 80, 122),\n"
"                                stop: 0.5  rgb(80, 80, 122), stop: 1.0  rgb(80, 80, 122));\n"
"    border: 2px solid  rgb(80, 80, 122);\n"
"    border-bottom-color:  rgb(80, 80, 122); /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 35ex;\n"
"    padding: 2px;\n"
"     color:  rgb(240, 250, 255);\n"
"    font: 10pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 rgb(180, 180, 222), stop: 0.4 rgb(180, 180, 222),\n"
"                                stop: 0.5 rgb(180, 180, 222), stop: 1.0 rgb(180, 180, 222));\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: rgb(180, 180, 222);\n"
"    border-bottom-color: rgb(180, 180, 222); /* same as pane color */\n"
"    color: rgb(230, 250, 255);\n"
"    font: 10pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"\n"
"/* make use of negative margins for overlapping tabs */\n"
"QTabBar::tab:selected {\n"
"    /* expand/overlap to the left and right by 4px */\n"
"    margin-left: -4px;\n"
"    margin-right: -4px;\n"
"}\n"
"\n"
"QTabBar::tab:first:selected {\n"
"    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"    margin: 0; /* if there is only one tab, we don\'t want overlapping margins */\n"
"}")
        self.Widgets.setTabPosition(QtWidgets.QTabWidget.North)
        self.Widgets.setElideMode(QtCore.Qt.ElideNone)
        self.Widgets.setDocumentMode(False)
        self.Widgets.setTabsClosable(False)
        self.Widgets.setObjectName("Widgets")
        self.Currencies = QtWidgets.QWidget()
        self.Currencies.setStyleSheet("background-color: rgb(22, 22, 34);\n"
"\n"
" ")
        self.Currencies.setObjectName("Currencies")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Currencies)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.Currencies)
        self.scrollArea.setStyleSheet("QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(55, 110, 190);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 1098))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 1080))
        self.frame.setMaximumSize(QtCore.QSize(1920, 1080))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, 10, 321, 1001))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.CURRENCIES = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.CURRENCIES.setContentsMargins(10, 10, 0, 0)
        self.CURRENCIES.setSpacing(20)
        self.CURRENCIES.setObjectName("CURRENCIES")
        self.USD = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.USD.setMinimumSize(QtCore.QSize(150, 50))
        self.USD.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.USD.setFont(font)
        self.USD.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color:rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.USD.setObjectName("USD")
        self.CURRENCIES.addWidget(self.USD)
        self.EUR = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.EUR.setMinimumSize(QtCore.QSize(150, 50))
        self.EUR.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(30)
        self.EUR.setFont(font)
        self.EUR.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color:rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.EUR.setObjectName("EUR")
        self.CURRENCIES.addWidget(self.EUR)
        self.GBP = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.GBP.setEnabled(True)
        self.GBP.setMinimumSize(QtCore.QSize(150, 50))
        self.GBP.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(30)
        self.GBP.setFont(font)
        self.GBP.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color:rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.GBP.setObjectName("GBP")
        self.CURRENCIES.addWidget(self.GBP)
        self.TRY = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TRY.setMinimumSize(QtCore.QSize(150, 50))
        self.TRY.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(30)
        self.TRY.setFont(font)
        self.TRY.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color:rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.TRY.setObjectName("TRY")
        self.CURRENCIES.addWidget(self.TRY)
        self.JPY = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.JPY.setMinimumSize(QtCore.QSize(150, 50))
        self.JPY.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(30)
        self.JPY.setFont(font)
        self.JPY.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.JPY.setObjectName("JPY")
        self.CURRENCIES.addWidget(self.JPY)
        self.AUD = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.AUD.setMinimumSize(QtCore.QSize(150, 50))
        self.AUD.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(30)
        self.AUD.setFont(font)
        self.AUD.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.AUD.setObjectName("AUD")
        self.CURRENCIES.addWidget(self.AUD)
        self.BTC = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.BTC.setMinimumSize(QtCore.QSize(150, 50))
        self.BTC.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(30)
        self.BTC.setFont(font)
        self.BTC.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.BTC.setObjectName("BTC")
        self.CURRENCIES.addWidget(self.BTC)
        self.ETH = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ETH.setEnabled(True)
        self.ETH.setMinimumSize(QtCore.QSize(150, 50))
        self.ETH.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(30)
        self.ETH.setFont(font)
        self.ETH.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.ETH.setObjectName("ETH")
        self.CURRENCIES.addWidget(self.ETH)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(310, 10, 1290, 1000))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.NUMBERS_CURRENCIES = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.NUMBERS_CURRENCIES.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.NUMBERS_CURRENCIES.setContentsMargins(10, 10, 1000, 0)
        self.NUMBERS_CURRENCIES.setSpacing(20)
        self.NUMBERS_CURRENCIES.setObjectName("NUMBERS_CURRENCIES")
        self.Currency_USD = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Currency_USD.setMinimumSize(QtCore.QSize(150, 50))
        self.Currency_USD.setMaximumSize(QtCore.QSize(153, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Currency_USD.setFont(font)
        self.Currency_USD.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Currency_USD.setObjectName("Currency_USD")
        self.NUMBERS_CURRENCIES.addWidget(self.Currency_USD)
        self.Currency_EUR = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Currency_EUR.setMinimumSize(QtCore.QSize(150, 50))
        self.Currency_EUR.setMaximumSize(QtCore.QSize(153, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(22)
        self.Currency_EUR.setFont(font)
        self.Currency_EUR.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Currency_EUR.setObjectName("Currency_EUR")
        self.NUMBERS_CURRENCIES.addWidget(self.Currency_EUR)
        self.Currency_GBP = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Currency_GBP.setMinimumSize(QtCore.QSize(150, 50))
        self.Currency_GBP.setMaximumSize(QtCore.QSize(153, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Currency_GBP.setFont(font)
        self.Currency_GBP.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Currency_GBP.setObjectName("Currency_GBP")
        self.NUMBERS_CURRENCIES.addWidget(self.Currency_GBP)
        self.Currency_TRY = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Currency_TRY.setMinimumSize(QtCore.QSize(150, 50))
        self.Currency_TRY.setMaximumSize(QtCore.QSize(153, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Currency_TRY.setFont(font)
        self.Currency_TRY.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Currency_TRY.setObjectName("Currency_TRY")
        self.NUMBERS_CURRENCIES.addWidget(self.Currency_TRY)
        self.Currency_JPY = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Currency_JPY.setMinimumSize(QtCore.QSize(150, 50))
        self.Currency_JPY.setMaximumSize(QtCore.QSize(153, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Currency_JPY.setFont(font)
        self.Currency_JPY.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Currency_JPY.setObjectName("Currency_JPY")
        self.NUMBERS_CURRENCIES.addWidget(self.Currency_JPY)
        self.Currency_AUD = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Currency_AUD.setMinimumSize(QtCore.QSize(150, 50))
        self.Currency_AUD.setMaximumSize(QtCore.QSize(153, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setKerning(True)
        self.Currency_AUD.setFont(font)
        self.Currency_AUD.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Currency_AUD.setObjectName("Currency_AUD")
        self.NUMBERS_CURRENCIES.addWidget(self.Currency_AUD)
        self.Currency_BTC = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Currency_BTC.setMinimumSize(QtCore.QSize(150, 50))
        self.Currency_BTC.setMaximumSize(QtCore.QSize(153, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Currency_BTC.setFont(font)
        self.Currency_BTC.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Currency_BTC.setObjectName("Currency_BTC")
        self.NUMBERS_CURRENCIES.addWidget(self.Currency_BTC)
        self.Currency_ETH = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Currency_ETH.setMinimumSize(QtCore.QSize(150, 50))
        self.Currency_ETH.setMaximumSize(QtCore.QSize(153, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Currency_ETH.setFont(font)
        self.Currency_ETH.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Currency_ETH.setObjectName("Currency_ETH")
        self.NUMBERS_CURRENCIES.addWidget(self.Currency_ETH)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.Widgets.addTab(self.Currencies, "")
        self.Products = QtWidgets.QWidget()
        self.Products.setStyleSheet("background-color: rgb(22, 22, 34);\n"
"")
        self.Products.setObjectName("Products")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Products)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.Products)
        self.scrollArea_3.setStyleSheet("QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(55, 110, 190);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 507, 1098))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 1080))
        self.frame_3.setMaximumSize(QtCore.QSize(1920, 1080))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 301, 1021))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.PRODUCTS = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.PRODUCTS.setContentsMargins(10, 10, 0, 0)
        self.PRODUCTS.setSpacing(10)
        self.PRODUCTS.setObjectName("PRODUCTS")
        self.Gold = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Gold.setMinimumSize(QtCore.QSize(150, 50))
        self.Gold.setMaximumSize(QtCore.QSize(230, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Gold.setFont(font)
        self.Gold.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Gold.setObjectName("Gold")
        self.PRODUCTS.addWidget(self.Gold)
        self.Silver = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Silver.setMinimumSize(QtCore.QSize(150, 50))
        self.Silver.setMaximumSize(QtCore.QSize(230, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Silver.setFont(font)
        self.Silver.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Silver.setObjectName("Silver")
        self.PRODUCTS.addWidget(self.Silver)
        self.Platinum = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Platinum.setMinimumSize(QtCore.QSize(150, 50))
        self.Platinum.setMaximumSize(QtCore.QSize(230, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Platinum.setFont(font)
        self.Platinum.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Platinum.setObjectName("Platinum")
        self.PRODUCTS.addWidget(self.Platinum)
        self.Palladium = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Palladium.setMinimumSize(QtCore.QSize(150, 50))
        self.Palladium.setMaximumSize(QtCore.QSize(230, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Palladium.setFont(font)
        self.Palladium.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color:rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Palladium.setObjectName("Palladium")
        self.PRODUCTS.addWidget(self.Palladium)
        self.Oil_Brent = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Oil_Brent.setMinimumSize(QtCore.QSize(150, 50))
        self.Oil_Brent.setMaximumSize(QtCore.QSize(230, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Oil_Brent.setFont(font)
        self.Oil_Brent.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Oil_Brent.setObjectName("Oil_Brent")
        self.PRODUCTS.addWidget(self.Oil_Brent)
        self.Oil_WTI = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Oil_WTI.setMinimumSize(QtCore.QSize(150, 50))
        self.Oil_WTI.setMaximumSize(QtCore.QSize(230, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Oil_WTI.setFont(font)
        self.Oil_WTI.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Oil_WTI.setObjectName("Oil_WTI")
        self.PRODUCTS.addWidget(self.Oil_WTI)
        self.Gas = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Gas.setMinimumSize(QtCore.QSize(150, 50))
        self.Gas.setMaximumSize(QtCore.QSize(230, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Gas.setFont(font)
        self.Gas.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Gas.setObjectName("Gas")
        self.PRODUCTS.addWidget(self.Gas)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(300, 0, 261, 1021))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.PRODUCTS_NUMBERS = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.PRODUCTS_NUMBERS.setContentsMargins(10, 10, 9, 0)
        self.PRODUCTS_NUMBERS.setSpacing(10)
        self.PRODUCTS_NUMBERS.setObjectName("PRODUCTS_NUMBERS")
        self.Course_Gold = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Course_Gold.setMinimumSize(QtCore.QSize(150, 50))
        self.Course_Gold.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Course_Gold.setFont(font)
        self.Course_Gold.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Course_Gold.setObjectName("Course_Gold")
        self.PRODUCTS_NUMBERS.addWidget(self.Course_Gold)
        self.Course_Silver = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Course_Silver.setMinimumSize(QtCore.QSize(150, 50))
        self.Course_Silver.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Course_Silver.setFont(font)
        self.Course_Silver.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Course_Silver.setObjectName("Course_Silver")
        self.PRODUCTS_NUMBERS.addWidget(self.Course_Silver)
        self.Course_Platinum = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Course_Platinum.setMinimumSize(QtCore.QSize(150, 50))
        self.Course_Platinum.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Course_Platinum.setFont(font)
        self.Course_Platinum.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Course_Platinum.setObjectName("Course_Platinum")
        self.PRODUCTS_NUMBERS.addWidget(self.Course_Platinum)
        self.Course_Palladium = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Course_Palladium.setMinimumSize(QtCore.QSize(150, 50))
        self.Course_Palladium.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Course_Palladium.setFont(font)
        self.Course_Palladium.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Course_Palladium.setObjectName("Course_Palladium")
        self.PRODUCTS_NUMBERS.addWidget(self.Course_Palladium)
        self.Course_Brent = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Course_Brent.setMinimumSize(QtCore.QSize(150, 50))
        self.Course_Brent.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Course_Brent.setFont(font)
        self.Course_Brent.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Course_Brent.setObjectName("Course_Brent")
        self.PRODUCTS_NUMBERS.addWidget(self.Course_Brent)
        self.Course_WTI = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Course_WTI.setMinimumSize(QtCore.QSize(150, 50))
        self.Course_WTI.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Course_WTI.setFont(font)
        self.Course_WTI.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Course_WTI.setObjectName("Course_WTI")
        self.PRODUCTS_NUMBERS.addWidget(self.Course_WTI)
        self.Course_Gas = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Course_Gas.setMinimumSize(QtCore.QSize(150, 50))
        self.Course_Gas.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Course_Gas.setFont(font)
        self.Course_Gas.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Course_Gas.setObjectName("Course_Gas")
        self.PRODUCTS_NUMBERS.addWidget(self.Course_Gas)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.addWidget(self.scrollArea_3)
        self.Widgets.addTab(self.Products, "")
        self.Stocks = QtWidgets.QWidget()
        self.Stocks.setStyleSheet("background-color: rgb(22, 22, 34);")
        self.Stocks.setObjectName("Stocks")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Stocks)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.Stocks)
        self.scrollArea_4.setStyleSheet("\n"
"\n"
"")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 507, 1098))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 1080))
        self.frame_4.setMaximumSize(QtCore.QSize(1920, 1080))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(290, 0, 261, 1071))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.NUMBERS_STOCKS = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.NUMBERS_STOCKS.setContentsMargins(10, 10, 0, 0)
        self.NUMBERS_STOCKS.setSpacing(10)
        self.NUMBERS_STOCKS.setObjectName("NUMBERS_STOCKS")
        self.Stocks_Sberbank = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Stocks_Sberbank.setMinimumSize(QtCore.QSize(150, 50))
        self.Stocks_Sberbank.setMaximumSize(QtCore.QSize(174, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Stocks_Sberbank.setFont(font)
        self.Stocks_Sberbank.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Stocks_Sberbank.setObjectName("Stocks_Sberbank")
        self.NUMBERS_STOCKS.addWidget(self.Stocks_Sberbank)
        self.Stocks_Gazprom = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Stocks_Gazprom.setMinimumSize(QtCore.QSize(150, 50))
        self.Stocks_Gazprom.setMaximumSize(QtCore.QSize(174, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Stocks_Gazprom.setFont(font)
        self.Stocks_Gazprom.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Stocks_Gazprom.setObjectName("Stocks_Gazprom")
        self.NUMBERS_STOCKS.addWidget(self.Stocks_Gazprom)
        self.Stocks_Lukoil = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Stocks_Lukoil.setMinimumSize(QtCore.QSize(150, 50))
        self.Stocks_Lukoil.setMaximumSize(QtCore.QSize(174, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Stocks_Lukoil.setFont(font)
        self.Stocks_Lukoil.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Stocks_Lukoil.setObjectName("Stocks_Lukoil")
        self.NUMBERS_STOCKS.addWidget(self.Stocks_Lukoil)
        self.Stocks_Yandex = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Stocks_Yandex.setMinimumSize(QtCore.QSize(150, 50))
        self.Stocks_Yandex.setMaximumSize(QtCore.QSize(174, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Stocks_Yandex.setFont(font)
        self.Stocks_Yandex.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Stocks_Yandex.setObjectName("Stocks_Yandex")
        self.NUMBERS_STOCKS.addWidget(self.Stocks_Yandex)
        self.Stocks_Tesla = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Stocks_Tesla.setMinimumSize(QtCore.QSize(150, 50))
        self.Stocks_Tesla.setMaximumSize(QtCore.QSize(174, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Stocks_Tesla.setFont(font)
        self.Stocks_Tesla.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Stocks_Tesla.setObjectName("Stocks_Tesla")
        self.NUMBERS_STOCKS.addWidget(self.Stocks_Tesla)
        self.Stocks_Apple = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Stocks_Apple.setMinimumSize(QtCore.QSize(150, 50))
        self.Stocks_Apple.setMaximumSize(QtCore.QSize(174, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Stocks_Apple.setFont(font)
        self.Stocks_Apple.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Stocks_Apple.setObjectName("Stocks_Apple")
        self.NUMBERS_STOCKS.addWidget(self.Stocks_Apple)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 291, 1071))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.STOCKS = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.STOCKS.setContentsMargins(10, 10, 0, 0)
        self.STOCKS.setSpacing(10)
        self.STOCKS.setObjectName("STOCKS")
        self.Sberbank = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Sberbank.setMinimumSize(QtCore.QSize(150, 50))
        self.Sberbank.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Sberbank.setFont(font)
        self.Sberbank.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Sberbank.setObjectName("Sberbank")
        self.STOCKS.addWidget(self.Sberbank)
        self.Gazprom = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Gazprom.setMinimumSize(QtCore.QSize(150, 50))
        self.Gazprom.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Gazprom.setFont(font)
        self.Gazprom.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Gazprom.setObjectName("Gazprom")
        self.STOCKS.addWidget(self.Gazprom)
        self.Lukoil = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Lukoil.setMinimumSize(QtCore.QSize(150, 50))
        self.Lukoil.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Lukoil.setFont(font)
        self.Lukoil.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Lukoil.setObjectName("Lukoil")
        self.STOCKS.addWidget(self.Lukoil)
        self.Yandex = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Yandex.setMinimumSize(QtCore.QSize(150, 50))
        self.Yandex.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Yandex.setFont(font)
        self.Yandex.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Yandex.setObjectName("Yandex")
        self.STOCKS.addWidget(self.Yandex)
        self.Tesla = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Tesla.setMinimumSize(QtCore.QSize(150, 50))
        self.Tesla.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Tesla.setFont(font)
        self.Tesla.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Tesla.setObjectName("Tesla")
        self.STOCKS.addWidget(self.Tesla)
        self.Apple = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Apple.setMinimumSize(QtCore.QSize(150, 50))
        self.Apple.setMaximumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        self.Apple.setFont(font)
        self.Apple.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color:rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Apple.setObjectName("Apple")
        self.STOCKS.addWidget(self.Apple)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8.addWidget(self.scrollArea_4)
        self.Widgets.addTab(self.Stocks, "")
        self.Converter = QtWidgets.QWidget()
        self.Converter.setObjectName("Converter")
        self.Input_currency = QtWidgets.QLineEdit(self.Converter)
        self.Input_currency.setGeometry(QtCore.QRect(20, 20, 250, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.Input_currency.setFont(font)
        self.Input_currency.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}")
        self.Input_currency.setObjectName("Input_currency")
        self.Input_amount = QtWidgets.QLineEdit(self.Converter)
        self.Input_amount.setGeometry(QtCore.QRect(20, 100, 250, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.Input_amount.setFont(font)
        self.Input_amount.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}")
        self.Input_amount.setObjectName("Input_amount")
        self.Output_currency = QtWidgets.QLineEdit(self.Converter)
        self.Output_currency.setGeometry(QtCore.QRect(20, 180, 250, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.Output_currency.setFont(font)
        self.Output_currency.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}")
        self.Output_currency.setObjectName("Output_currency")
        self.Convert_Button = QtWidgets.QPushButton(self.Converter)
        self.Convert_Button.setGeometry(QtCore.QRect(20, 360, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(16)
        self.Convert_Button.setFont(font)
        self.Convert_Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: rgb(72, 72, 88);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    color: rgb(85, 170, 255)\n"
"    \n"
"}")
        self.Convert_Button.setObjectName("Convert_Button")
        self.Output_amount = QtWidgets.QLabel(self.Converter)
        self.Output_amount.setGeometry(QtCore.QRect(20, 260, 250, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.Output_amount.setFont(font)
        self.Output_amount.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: rgb(145, 145, 155);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.Output_amount.setObjectName("Output_amount")
        self.Widgets.addTab(self.Converter, "")
        self.Additionally = QtWidgets.QWidget()
        self.Additionally.setStyleSheet("background-color: rgb(22, 22, 34);\n"
"")
        self.Additionally.setObjectName("Additionally")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Additionally)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Additionally)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setStyleSheet("QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(55, 110, 190);\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -685, 507, 1098))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 1080))
        self.frame_2.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Group_Excel = QtWidgets.QGroupBox(self.frame_2)
        self.Group_Excel.setGeometry(QtCore.QRect(10, 10, 420, 290))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Group_Excel.setFont(font)
        self.Group_Excel.setStyleSheet("QGroupBox {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.Group_Excel.setObjectName("Group_Excel")
        self.Button_Excel = QtWidgets.QPushButton(self.Group_Excel)
        self.Button_Excel.setGeometry(QtCore.QRect(20, 180, 200, 80))
        self.Button_Excel.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        self.Button_Excel.setFont(font)
        self.Button_Excel.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: rgb(72, 72, 88);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    color: rgb(85, 170, 255)\n"
"    \n"
"}")
        self.Button_Excel.setObjectName("Button_Excel")
        self.Text_for_Excel = QtWidgets.QLabel(self.Group_Excel)
        self.Text_for_Excel.setGeometry(QtCore.QRect(10, 20, 391, 131))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.Text_for_Excel.setFont(font)
        self.Text_for_Excel.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.Text_for_Excel.setObjectName("Text_for_Excel")
        self.Group_Email = QtWidgets.QGroupBox(self.frame_2)
        self.Group_Email.setGeometry(QtCore.QRect(10, 340, 420, 400))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Group_Email.setFont(font)
        self.Group_Email.setStyleSheet("QGroupBox {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.Group_Email.setObjectName("Group_Email")
        self.Text_for_Email = QtWidgets.QLabel(self.Group_Email)
        self.Text_for_Email.setGeometry(QtCore.QRect(10, 20, 390, 130))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.Text_for_Email.setFont(font)
        self.Text_for_Email.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.Text_for_Email.setObjectName("Text_for_Email")
        self.Enter_email = QtWidgets.QLineEdit(self.Group_Email)
        self.Enter_email.setGeometry(QtCore.QRect(10, 170, 390, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.Enter_email.setFont(font)
        self.Enter_email.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}")
        self.Enter_email.setText("")
        self.Enter_email.setObjectName("Enter_email")
        self.Enter_percentage_Email = QtWidgets.QLineEdit(self.Group_Email)
        self.Enter_percentage_Email.setGeometry(QtCore.QRect(10, 240, 176, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.Enter_percentage_Email.setFont(font)
        self.Enter_percentage_Email.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}")
        self.Enter_percentage_Email.setText("")
        self.Enter_percentage_Email.setObjectName("Enter_percentage_Email")
        self.Button_Email = QtWidgets.QPushButton(self.Group_Email)
        self.Button_Email.setGeometry(QtCore.QRect(10, 300, 200, 80))
        self.Button_Email.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        self.Button_Email.setFont(font)
        self.Button_Email.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: rgb(72, 72, 88);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    color: rgb(85, 170, 255)\n"
"    \n"
"}")
        self.Button_Email.setObjectName("Button_Email")
        self.Group_percentage = QtWidgets.QGroupBox(self.frame_2)
        self.Group_percentage.setGeometry(QtCore.QRect(10, 770, 220, 290))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Group_percentage.setFont(font)
        self.Group_percentage.setStyleSheet("QGroupBox {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.Group_percentage.setObjectName("Group_percentage")
        self.Text_for_percentage = QtWidgets.QLabel(self.Group_percentage)
        self.Text_for_percentage.setGeometry(QtCore.QRect(10, 20, 200, 121))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.Text_for_percentage.setFont(font)
        self.Text_for_percentage.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.Text_for_percentage.setObjectName("Text_for_percentage")
        self.Enter_percentage = QtWidgets.QLineEdit(self.Group_percentage)
        self.Enter_percentage.setGeometry(QtCore.QRect(10, 153, 200, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.Enter_percentage.setFont(font)
        self.Enter_percentage.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}")
        self.Enter_percentage.setText("")
        self.Enter_percentage.setObjectName("Enter_percentage")
        self.Button_percentage = QtWidgets.QPushButton(self.Group_percentage)
        self.Button_percentage.setGeometry(QtCore.QRect(10, 215, 200, 60))
        self.Button_percentage.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        self.Button_percentage.setFont(font)
        self.Button_percentage.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: rgb(72, 72, 88);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    color: rgb(85, 170, 255)\n"
"    \n"
"}")
        self.Button_percentage.setObjectName("Button_percentage")
        self.Group_weather = QtWidgets.QGroupBox(self.frame_2)
        self.Group_weather.setGeometry(QtCore.QRect(270, 770, 220, 290))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Group_weather.setFont(font)
        self.Group_weather.setStyleSheet("QGroupBox {\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.Group_weather.setObjectName("Group_weather")
        self.Text_for_percentage_2 = QtWidgets.QLabel(self.Group_weather)
        self.Text_for_percentage_2.setGeometry(QtCore.QRect(10, 20, 200, 121))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.Text_for_percentage_2.setFont(font)
        self.Text_for_percentage_2.setStyleSheet("QLabel {\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.Text_for_percentage_2.setObjectName("Text_for_percentage_2")
        self.Enter_percentage_2 = QtWidgets.QLineEdit(self.Group_weather)
        self.Enter_percentage_2.setGeometry(QtCore.QRect(10, 153, 200, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.Enter_percentage_2.setFont(font)
        self.Enter_percentage_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"}")
        self.Enter_percentage_2.setText("")
        self.Enter_percentage_2.setObjectName("Enter_percentage_2")
        self.Button_percentage_2 = QtWidgets.QPushButton(self.Group_weather)
        self.Button_percentage_2.setGeometry(QtCore.QRect(10, 215, 200, 60))
        self.Button_percentage_2.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        self.Button_percentage_2.setFont(font)
        self.Button_percentage_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(27, 27, 42);\n"
"    border-radius: 20px;\n"
"    color: rgb(72, 72, 88);\n"
"    padding-left: 20px ;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(35, 35, 54);\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(46, 46, 71);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(44, 44, 68);\n"
"    color: rgb(85, 170, 255)\n"
"    \n"
"}")
        self.Button_percentage_2.setObjectName("Button_percentage_2")
        self.verticalLayout_5.addWidget(self.frame_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.Widgets.addTab(self.Additionally, "")
        self.Information = QtWidgets.QWidget()
        self.Information.setObjectName("Information")
        self.Widgets.addTab(self.Information, "")
        self.verticalLayout.addWidget(self.Widgets)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 563, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.Widgets.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.USD.setText(_translate("MainWindow", "USD"))
        self.EUR.setText(_translate("MainWindow", "EUR"))
        self.GBP.setText(_translate("MainWindow", "GBP"))
        self.TRY.setText(_translate("MainWindow", "TRY"))
        self.JPY.setText(_translate("MainWindow", "JPY"))
        self.AUD.setText(_translate("MainWindow", "AUD"))
        self.BTC.setText(_translate("MainWindow", "BTC"))
        self.ETH.setText(_translate("MainWindow", "ETH"))
        self.Currency_USD.setText(_translate("MainWindow", "Сurrency_USD"))
        self.Currency_EUR.setText(_translate("MainWindow", "Currency_EUR"))
        self.Currency_GBP.setText(_translate("MainWindow", "Currency_GBP"))
        self.Currency_TRY.setText(_translate("MainWindow", "Currency_TRY"))
        self.Currency_JPY.setText(_translate("MainWindow", "Currency_JPY"))
        self.Currency_AUD.setText(_translate("MainWindow", "Currency_AUD"))
        self.Currency_BTC.setText(_translate("MainWindow", "Currency_BTC"))
        self.Currency_ETH.setText(_translate("MainWindow", "Currency_ETH"))
        self.Widgets.setTabText(self.Widgets.indexOf(self.Currencies), _translate("MainWindow", "Валюты"))
        self.Gold.setText(_translate("MainWindow", "Золото"))
        self.Silver.setText(_translate("MainWindow", "Серебро"))
        self.Platinum.setText(_translate("MainWindow", "Платина"))
        self.Palladium.setText(_translate("MainWindow", "Палладий"))
        self.Oil_Brent.setText(_translate("MainWindow", "Нефть \"Brent\""))
        self.Oil_WTI.setText(_translate("MainWindow", "Нефть \"WTI\""))
        self.Gas.setText(_translate("MainWindow", "Природный газ"))
        self.Course_Gold.setText(_translate("MainWindow", "Курс зололта"))
        self.Course_Silver.setText(_translate("MainWindow", "Курс серебра"))
        self.Course_Platinum.setText(_translate("MainWindow", "Курс платины"))
        self.Course_Palladium.setText(_translate("MainWindow", "Курс паладия"))
        self.Course_Brent.setText(_translate("MainWindow", "Курс нефти \"BRENT\""))
        self.Course_WTI.setText(_translate("MainWindow", "Курс нефти \"WTI\""))
        self.Course_Gas.setText(_translate("MainWindow", "Курс природного газа"))
        self.Widgets.setTabText(self.Widgets.indexOf(self.Products), _translate("MainWindow", "Товары"))
        self.Stocks_Sberbank.setText(_translate("MainWindow", "Акции Сбербанк"))
        self.Stocks_Gazprom.setText(_translate("MainWindow", "Акции Газпром"))
        self.Stocks_Lukoil.setText(_translate("MainWindow", "Акции Лукойл"))
        self.Stocks_Yandex.setText(_translate("MainWindow", "Акции Яндекс"))
        self.Stocks_Tesla.setText(_translate("MainWindow", "Акции Тесла"))
        self.Stocks_Apple.setText(_translate("MainWindow", "Акции Apple"))
        self.Sberbank.setText(_translate("MainWindow", "Сбербанк"))
        self.Gazprom.setText(_translate("MainWindow", "Газпром"))
        self.Lukoil.setText(_translate("MainWindow", "Лукойл"))
        self.Yandex.setText(_translate("MainWindow", "Яндекс"))
        self.Tesla.setText(_translate("MainWindow", "Тесла"))
        self.Apple.setText(_translate("MainWindow", "Apple"))
        self.Widgets.setTabText(self.Widgets.indexOf(self.Stocks), _translate("MainWindow", "Акции"))
        self.Input_currency.setPlaceholderText(_translate("MainWindow", "From the currency:"))
        self.Input_amount.setPlaceholderText(_translate("MainWindow", "The Amount:"))
        self.Output_currency.setPlaceholderText(_translate("MainWindow", "To the currency:"))
        self.Convert_Button.setText(_translate("MainWindow", "CONVERT"))
        self.Output_amount.setText(_translate("MainWindow", "I\'ll get it:"))
        self.Widgets.setTabText(self.Widgets.indexOf(self.Converter), _translate("MainWindow", "Конвертер"))
        self.Group_Excel.setTitle(_translate("MainWindow", "Excel"))
        self.Button_Excel.setText(_translate("MainWindow", "Создать Excel таблицу"))
        self.Text_for_Excel.setText(_translate("MainWindow", "Нажмите на конпку, чтобы создать таблицу Excel \n"
"с данными об изменениях валют \n"
"с начала работы программы."))
        self.Group_Email.setTitle(_translate("MainWindow", "Email"))
        self.Text_for_Email.setText(_translate("MainWindow", "Чтобы получать уведомления на почту \n"
"об изменениях валют на определённый процент,\n"
"введите свой Email и процент изменения валют."))
        self.Enter_email.setPlaceholderText(_translate("MainWindow", "Введите Email:"))
        self.Enter_percentage_Email.setPlaceholderText(_translate("MainWindow", "Введите процент:"))
        self.Button_Email.setText(_translate("MainWindow", "Рассылать уведомления"))
        self.Group_percentage.setTitle(_translate("MainWindow", "Изменения валют"))
        self.Text_for_percentage.setText(_translate("MainWindow", "Чтобы получать \n"
"уведомления \n"
"об изменениях валют \n"
"на определённый \n"
"процент,\n"
"введите процент \n"
"изменения валют."))
        self.Enter_percentage.setPlaceholderText(_translate("MainWindow", "Введите процент:"))
        self.Button_percentage.setText(_translate("MainWindow", "Рассылать уведомления"))
        self.Group_weather.setTitle(_translate("MainWindow", "Погода"))
        self.Text_for_percentage_2.setText(_translate("MainWindow", "Чтобы следить \n"
"за погодой \n"
"в своём городе, \n"
"введите город."))
        self.Enter_percentage_2.setPlaceholderText(_translate("MainWindow", "Введите город:"))
        self.Button_percentage_2.setText(_translate("MainWindow", "Отслеживать"))
        self.Widgets.setTabText(self.Widgets.indexOf(self.Additionally), _translate("MainWindow", "Дополнительно"))
        self.Widgets.setTabText(self.Widgets.indexOf(self.Information), _translate("MainWindow", "О программе"))


