# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 682)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(5)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setLineWidth(0)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(120, 230, 130);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setLineWidth(0)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet("QPushButton {\n"
"\n"
"    color: rgb(120, 230, 130);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color:  rgb(177, 244, 92);\n"
"}")
        self.Btn_Toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/toggle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Toggle.setIcon(icon)
        self.Btn_Toggle.setIconSize(QtCore.QSize(30, 30))
        self.Btn_Toggle.setAutoRepeatDelay(298)
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setStyleSheet("border: none;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setLineWidth(0)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setStyleSheet("border: none;")
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setLineWidth(0)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border: none;")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setLineWidth(0)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_Home = QtWidgets.QPushButton(self.frame_left_menu)
        self.btn_Home.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_Home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Home.setAutoFillBackground(False)
        self.btn_Home.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    padding-left: 50;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 230, 130);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:  rgb(177, 244, 92)\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Home.setIcon(icon1)
        self.btn_Home.setIconSize(QtCore.QSize(50, 40))
        self.btn_Home.setShortcut("")
        self.btn_Home.setCheckable(False)
        self.btn_Home.setAutoRepeat(False)
        self.btn_Home.setAutoRepeatDelay(300)
        self.btn_Home.setObjectName("btn_Home")
        self.verticalLayout_3.addWidget(self.btn_Home)
        self.btn_Converter = QtWidgets.QPushButton(self.frame_left_menu)
        self.btn_Converter.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_Converter.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    padding-left: 72;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 230, 130);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:  rgb(177, 244, 92)\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/converter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Converter.setIcon(icon2)
        self.btn_Converter.setIconSize(QtCore.QSize(50, 30))
        self.btn_Converter.setObjectName("btn_Converter")
        self.verticalLayout_3.addWidget(self.btn_Converter)
        self.btn_Excel = QtWidgets.QPushButton(self.frame_left_menu)
        self.btn_Excel.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_Excel.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    padding-left: 54;    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 230, 130);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:  rgb(177, 244, 92)\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Excel.setIcon(icon3)
        self.btn_Excel.setIconSize(QtCore.QSize(50, 25))
        self.btn_Excel.setObjectName("btn_Excel")
        self.verticalLayout_3.addWidget(self.btn_Excel)
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_top_menus.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setLineWidth(0)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setLineWidth(0)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setTabletTracking(False)
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Home = QtWidgets.QWidget()
        self.page_Home.setObjectName("page_Home")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_Home)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_content_home = QtWidgets.QFrame(self.page_Home)
        self.frame_content_home.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.frame_content_home.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_home.setLineWidth(0)
        self.frame_content_home.setObjectName("frame_content_home")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_content_home)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_content_home)
        self.scrollArea.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(35, 35, 35);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color:rgb(70, 70, 70);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(120, 230, 130);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(177, 244, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(35, 35, 35);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(120, 230, 130);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(177, 244, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(35, 35, 35);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(120, 230, 130);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color:rgb(177, 244, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR - HOMEWORK */\n"
"QScrollBar:horizontal {\n"
"   \n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"\n"
"}\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 895, 1740))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_btn_Information = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_btn_Information.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_btn_Information.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_btn_Information.setStyleSheet("")
        self.frame_btn_Information.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btn_Information.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_btn_Information.setLineWidth(0)
        self.frame_btn_Information.setObjectName("frame_btn_Information")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_btn_Information)
        self.horizontalLayout_4.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_top_btn_information = QtWidgets.QFrame(self.frame_btn_Information)
        self.frame_top_btn_information.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_top_btn_information.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_top_btn_information.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_top_btn_information.setAutoFillBackground(False)
        self.frame_top_btn_information.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btn_information.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_top_btn_information.setObjectName("frame_top_btn_information")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_top_btn_information)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_TO_THE_RUB = QtWidgets.QLabel(self.frame_top_btn_information)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_TO_THE_RUB.setFont(font)
        self.label_TO_THE_RUB.setStyleSheet("color: rgb(70, 70, 70);\n"
"")
        self.label_TO_THE_RUB.setObjectName("label_TO_THE_RUB")
        self.verticalLayout_32.addWidget(self.label_TO_THE_RUB)
        self.horizontalLayout_4.addWidget(self.frame_top_btn_information)
        self.btn_Information = QtWidgets.QPushButton(self.frame_btn_Information)
        self.btn_Information.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_Information.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_Information.setStyleSheet("QPushButton {\n"
"    border-radius: 20%;\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    background-color:rgb(44, 44, 44);\n"
"    padding-left: 1px;\n"
"    padding-bottom: -1.5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 230, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(177, 244, 92)\n"
"}\n"
"\n"
"")
        self.btn_Information.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/flag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Information.setIcon(icon4)
        self.btn_Information.setObjectName("btn_Information")
        self.horizontalLayout_4.addWidget(self.btn_Information)
        self.verticalLayout_11.addWidget(self.frame_btn_Information)
        self.frame_scollArea = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_scollArea.setMinimumSize(QtCore.QSize(0, 1700))
        self.frame_scollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_scollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_scollArea.setObjectName("frame_scollArea")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_scollArea)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_with_value = QtWidgets.QFrame(self.frame_scollArea)
        self.frame_with_value.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_with_value.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frame_with_value.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.frame_with_value.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_with_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_with_value.setObjectName("frame_with_value")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_with_value)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_bg_Currencies = QtWidgets.QFrame(self.frame_with_value)
        self.frame_bg_Currencies.setStyleSheet("background-color: rgb(70, 70, 70);\n"
"border: none;\n"
"border-radius: 30px;")
        self.frame_bg_Currencies.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg_Currencies.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg_Currencies.setObjectName("frame_bg_Currencies")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_bg_Currencies)
        self.verticalLayout_13.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_13.setSpacing(12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.group_currencies = QtWidgets.QGroupBox(self.frame_bg_Currencies)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group_currencies.setFont(font)
        self.group_currencies.setStyleSheet("QGroupBox {\n"
"    border-radius: 30px;\n"
"    color: rgb(120, 230, 130);\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"}\n"
"\n"
"\n"
"")
        self.group_currencies.setObjectName("group_currencies")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.group_currencies)
        self.verticalLayout_14.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.USD_INF = QtWidgets.QFrame(self.group_currencies)
        self.USD_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.USD_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.USD_INF.setObjectName("USD_INF")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.USD_INF)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.USD = QtWidgets.QLabel(self.USD_INF)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.USD.setFont(font)
        self.USD.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.USD.setObjectName("USD")
        self.horizontalLayout_7.addWidget(self.USD)
        self.C_USD = QtWidgets.QLabel(self.USD_INF)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.C_USD.setFont(font)
        self.C_USD.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;")
        self.C_USD.setAlignment(QtCore.Qt.AlignCenter)
        self.C_USD.setObjectName("C_USD")
        self.horizontalLayout_7.addWidget(self.C_USD)
        self.verticalLayout_14.addWidget(self.USD_INF)
        self.EUR_INF = QtWidgets.QFrame(self.group_currencies)
        self.EUR_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.EUR_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.EUR_INF.setObjectName("EUR_INF")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.EUR_INF)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.EUR = QtWidgets.QLabel(self.EUR_INF)
        self.EUR.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";color: rgb(255, 255, 255);\n"
"padding-left: 20px;")
        self.EUR.setObjectName("EUR")
        self.horizontalLayout_8.addWidget(self.EUR)
        self.C_EUR = QtWidgets.QLabel(self.EUR_INF)
        self.C_EUR.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_EUR.setAlignment(QtCore.Qt.AlignCenter)
        self.C_EUR.setObjectName("C_EUR")
        self.horizontalLayout_8.addWidget(self.C_EUR)
        self.verticalLayout_14.addWidget(self.EUR_INF)
        self.GBP_INF = QtWidgets.QFrame(self.group_currencies)
        self.GBP_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.GBP_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GBP_INF.setObjectName("GBP_INF")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.GBP_INF)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.GBP = QtWidgets.QLabel(self.GBP_INF)
        self.GBP.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.GBP.setObjectName("GBP")
        self.horizontalLayout_9.addWidget(self.GBP)
        self.C_GBP = QtWidgets.QLabel(self.GBP_INF)
        self.C_GBP.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_GBP.setAlignment(QtCore.Qt.AlignCenter)
        self.C_GBP.setObjectName("C_GBP")
        self.horizontalLayout_9.addWidget(self.C_GBP)
        self.verticalLayout_14.addWidget(self.GBP_INF)
        self.TRY_INF = QtWidgets.QFrame(self.group_currencies)
        self.TRY_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TRY_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TRY_INF.setObjectName("TRY_INF")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.TRY_INF)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.TRY = QtWidgets.QLabel(self.TRY_INF)
        self.TRY.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.TRY.setObjectName("TRY")
        self.horizontalLayout_10.addWidget(self.TRY)
        self.C_TRY = QtWidgets.QLabel(self.TRY_INF)
        self.C_TRY.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_TRY.setAlignment(QtCore.Qt.AlignCenter)
        self.C_TRY.setObjectName("C_TRY")
        self.horizontalLayout_10.addWidget(self.C_TRY)
        self.verticalLayout_14.addWidget(self.TRY_INF)
        self.JPY_INF = QtWidgets.QFrame(self.group_currencies)
        self.JPY_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.JPY_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.JPY_INF.setObjectName("JPY_INF")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.JPY_INF)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.JPY = QtWidgets.QLabel(self.JPY_INF)
        self.JPY.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.JPY.setObjectName("JPY")
        self.horizontalLayout_11.addWidget(self.JPY)
        self.C_JPY = QtWidgets.QLabel(self.JPY_INF)
        self.C_JPY.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_JPY.setAlignment(QtCore.Qt.AlignCenter)
        self.C_JPY.setObjectName("C_JPY")
        self.horizontalLayout_11.addWidget(self.C_JPY)
        self.verticalLayout_14.addWidget(self.JPY_INF)
        self.AUD_INF = QtWidgets.QFrame(self.group_currencies)
        self.AUD_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AUD_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUD_INF.setObjectName("AUD_INF")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.AUD_INF)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.AUD = QtWidgets.QLabel(self.AUD_INF)
        self.AUD.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.AUD.setObjectName("AUD")
        self.horizontalLayout_12.addWidget(self.AUD)
        self.C_AUD = QtWidgets.QLabel(self.AUD_INF)
        self.C_AUD.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_AUD.setAlignment(QtCore.Qt.AlignCenter)
        self.C_AUD.setObjectName("C_AUD")
        self.horizontalLayout_12.addWidget(self.C_AUD)
        self.verticalLayout_14.addWidget(self.AUD_INF)
        self.BTC_INF = QtWidgets.QFrame(self.group_currencies)
        self.BTC_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BTC_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BTC_INF.setObjectName("BTC_INF")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.BTC_INF)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.BTC = QtWidgets.QLabel(self.BTC_INF)
        self.BTC.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.BTC.setObjectName("BTC")
        self.horizontalLayout_6.addWidget(self.BTC)
        self.C_BTC = QtWidgets.QLabel(self.BTC_INF)
        self.C_BTC.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_BTC.setAlignment(QtCore.Qt.AlignCenter)
        self.C_BTC.setObjectName("C_BTC")
        self.horizontalLayout_6.addWidget(self.C_BTC)
        self.verticalLayout_14.addWidget(self.BTC_INF)
        self.ETH_INF = QtWidgets.QFrame(self.group_currencies)
        self.ETH_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ETH_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ETH_INF.setObjectName("ETH_INF")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.ETH_INF)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ETH = QtWidgets.QLabel(self.ETH_INF)
        self.ETH.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.ETH.setObjectName("ETH")
        self.horizontalLayout_13.addWidget(self.ETH)
        self.C_ETH = QtWidgets.QLabel(self.ETH_INF)
        self.C_ETH.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_ETH.setAlignment(QtCore.Qt.AlignCenter)
        self.C_ETH.setObjectName("C_ETH")
        self.horizontalLayout_13.addWidget(self.C_ETH)
        self.verticalLayout_14.addWidget(self.ETH_INF)
        self.verticalLayout_13.addWidget(self.group_currencies)
        self.verticalLayout_12.addWidget(self.frame_bg_Currencies)
        self.frame_bg_Products = QtWidgets.QFrame(self.frame_with_value)
        self.frame_bg_Products.setStyleSheet("background-color: rgb(70, 70, 70);\n"
"border: none;\n"
"border-radius: 30px;")
        self.frame_bg_Products.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg_Products.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg_Products.setObjectName("frame_bg_Products")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_bg_Products)
        self.verticalLayout_16.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_16.setSpacing(12)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.group_products = QtWidgets.QGroupBox(self.frame_bg_Products)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group_products.setFont(font)
        self.group_products.setStyleSheet("QGroupBox {\n"
"    border-radius: 30px;\n"
"    color: rgb(120, 230, 130);\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"}\n"
"\n"
"\n"
"")
        self.group_products.setObjectName("group_products")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.group_products)
        self.verticalLayout_15.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.OilBrent_INF = QtWidgets.QFrame(self.group_products)
        self.OilBrent_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.OilBrent_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OilBrent_INF.setObjectName("OilBrent_INF")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.OilBrent_INF)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.OilBrent = QtWidgets.QLabel(self.OilBrent_INF)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.OilBrent.setFont(font)
        self.OilBrent.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.OilBrent.setObjectName("OilBrent")
        self.horizontalLayout_14.addWidget(self.OilBrent)
        self.C_OilBrent = QtWidgets.QLabel(self.OilBrent_INF)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.C_OilBrent.setFont(font)
        self.C_OilBrent.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;")
        self.C_OilBrent.setAlignment(QtCore.Qt.AlignCenter)
        self.C_OilBrent.setObjectName("C_OilBrent")
        self.horizontalLayout_14.addWidget(self.C_OilBrent)
        self.verticalLayout_15.addWidget(self.OilBrent_INF)
        self.OilWTI_INF = QtWidgets.QFrame(self.group_products)
        self.OilWTI_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.OilWTI_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OilWTI_INF.setObjectName("OilWTI_INF")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.OilWTI_INF)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.OilWTI = QtWidgets.QLabel(self.OilWTI_INF)
        self.OilWTI.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";color: rgb(255, 255, 255);\n"
"padding-left: 20px;")
        self.OilWTI.setObjectName("OilWTI")
        self.horizontalLayout_15.addWidget(self.OilWTI)
        self.C_OilWTI = QtWidgets.QLabel(self.OilWTI_INF)
        self.C_OilWTI.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_OilWTI.setAlignment(QtCore.Qt.AlignCenter)
        self.C_OilWTI.setObjectName("C_OilWTI")
        self.horizontalLayout_15.addWidget(self.C_OilWTI)
        self.verticalLayout_15.addWidget(self.OilWTI_INF)
        self.Gold_INF = QtWidgets.QFrame(self.group_products)
        self.Gold_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Gold_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Gold_INF.setObjectName("Gold_INF")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.Gold_INF)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Gold = QtWidgets.QLabel(self.Gold_INF)
        self.Gold.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Gold.setObjectName("Gold")
        self.horizontalLayout_16.addWidget(self.Gold)
        self.C_Gold = QtWidgets.QLabel(self.Gold_INF)
        self.C_Gold.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Gold.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Gold.setObjectName("C_Gold")
        self.horizontalLayout_16.addWidget(self.C_Gold)
        self.verticalLayout_15.addWidget(self.Gold_INF)
        self.Silver_INF = QtWidgets.QFrame(self.group_products)
        self.Silver_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Silver_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Silver_INF.setObjectName("Silver_INF")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.Silver_INF)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Silver = QtWidgets.QLabel(self.Silver_INF)
        self.Silver.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Silver.setObjectName("Silver")
        self.horizontalLayout_17.addWidget(self.Silver)
        self.C_Silver = QtWidgets.QLabel(self.Silver_INF)
        self.C_Silver.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Silver.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Silver.setObjectName("C_Silver")
        self.horizontalLayout_17.addWidget(self.C_Silver)
        self.verticalLayout_15.addWidget(self.Silver_INF)
        self.Platinum_INF = QtWidgets.QFrame(self.group_products)
        self.Platinum_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Platinum_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Platinum_INF.setObjectName("Platinum_INF")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.Platinum_INF)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.Platinum = QtWidgets.QLabel(self.Platinum_INF)
        self.Platinum.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Platinum.setObjectName("Platinum")
        self.horizontalLayout_18.addWidget(self.Platinum)
        self.C_Platinum = QtWidgets.QLabel(self.Platinum_INF)
        self.C_Platinum.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Platinum.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Platinum.setObjectName("C_Platinum")
        self.horizontalLayout_18.addWidget(self.C_Platinum)
        self.verticalLayout_15.addWidget(self.Platinum_INF)
        self.Palladium_INF = QtWidgets.QFrame(self.group_products)
        self.Palladium_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Palladium_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Palladium_INF.setObjectName("Palladium_INF")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.Palladium_INF)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.Palladium = QtWidgets.QLabel(self.Palladium_INF)
        self.Palladium.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Palladium.setObjectName("Palladium")
        self.horizontalLayout_19.addWidget(self.Palladium)
        self.C_Palladium = QtWidgets.QLabel(self.Palladium_INF)
        self.C_Palladium.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Palladium.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Palladium.setObjectName("C_Palladium")
        self.horizontalLayout_19.addWidget(self.C_Palladium)
        self.verticalLayout_15.addWidget(self.Palladium_INF)
        self.Gas_INF = QtWidgets.QFrame(self.group_products)
        self.Gas_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Gas_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Gas_INF.setObjectName("Gas_INF")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.Gas_INF)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.Gas = QtWidgets.QLabel(self.Gas_INF)
        self.Gas.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Gas.setObjectName("Gas")
        self.horizontalLayout_20.addWidget(self.Gas)
        self.C_Gas = QtWidgets.QLabel(self.Gas_INF)
        self.C_Gas.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Gas.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Gas.setObjectName("C_Gas")
        self.horizontalLayout_20.addWidget(self.C_Gas)
        self.verticalLayout_15.addWidget(self.Gas_INF)
        self.verticalLayout_16.addWidget(self.group_products)
        self.verticalLayout_12.addWidget(self.frame_bg_Products)
        self.frame_bg_Stocks = QtWidgets.QFrame(self.frame_with_value)
        self.frame_bg_Stocks.setStyleSheet("background-color: rgb(70, 70, 70);\n"
"border: none;\n"
"border-radius: 30px;")
        self.frame_bg_Stocks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg_Stocks.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg_Stocks.setObjectName("frame_bg_Stocks")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_bg_Stocks)
        self.verticalLayout_18.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_18.setSpacing(12)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.group_stocks = QtWidgets.QGroupBox(self.frame_bg_Stocks)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group_stocks.setFont(font)
        self.group_stocks.setStyleSheet("QGroupBox {\n"
"    border-radius: 30px;\n"
"    color: rgb(120, 230, 130);\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"}\n"
"\n"
"\n"
"")
        self.group_stocks.setObjectName("group_stocks")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.group_stocks)
        self.verticalLayout_17.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Sberbank_INF_ = QtWidgets.QFrame(self.group_stocks)
        self.Sberbank_INF_.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Sberbank_INF_.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Sberbank_INF_.setObjectName("Sberbank_INF_")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.Sberbank_INF_)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.Sberbank = QtWidgets.QLabel(self.Sberbank_INF_)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.Sberbank.setFont(font)
        self.Sberbank.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Sberbank.setObjectName("Sberbank")
        self.horizontalLayout_21.addWidget(self.Sberbank)
        self.C_Sberbank = QtWidgets.QLabel(self.Sberbank_INF_)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.C_Sberbank.setFont(font)
        self.C_Sberbank.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;")
        self.C_Sberbank.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Sberbank.setObjectName("C_Sberbank")
        self.horizontalLayout_21.addWidget(self.C_Sberbank)
        self.verticalLayout_17.addWidget(self.Sberbank_INF_)
        self.Gazprom_INF = QtWidgets.QFrame(self.group_stocks)
        self.Gazprom_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Gazprom_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Gazprom_INF.setObjectName("Gazprom_INF")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.Gazprom_INF)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.Gazprom = QtWidgets.QLabel(self.Gazprom_INF)
        self.Gazprom.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";color: rgb(255, 255, 255);\n"
"padding-left: 20px;")
        self.Gazprom.setObjectName("Gazprom")
        self.horizontalLayout_22.addWidget(self.Gazprom)
        self.C_Gazprom = QtWidgets.QLabel(self.Gazprom_INF)
        self.C_Gazprom.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Gazprom.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Gazprom.setObjectName("C_Gazprom")
        self.horizontalLayout_22.addWidget(self.C_Gazprom)
        self.verticalLayout_17.addWidget(self.Gazprom_INF)
        self.Lukoil_INF = QtWidgets.QFrame(self.group_stocks)
        self.Lukoil_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Lukoil_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Lukoil_INF.setObjectName("Lukoil_INF")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.Lukoil_INF)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.Lukoil = QtWidgets.QLabel(self.Lukoil_INF)
        self.Lukoil.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Lukoil.setObjectName("Lukoil")
        self.horizontalLayout_23.addWidget(self.Lukoil)
        self.C_Lukoil = QtWidgets.QLabel(self.Lukoil_INF)
        self.C_Lukoil.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Lukoil.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Lukoil.setObjectName("C_Lukoil")
        self.horizontalLayout_23.addWidget(self.C_Lukoil)
        self.verticalLayout_17.addWidget(self.Lukoil_INF)
        self.Yandex_INF = QtWidgets.QFrame(self.group_stocks)
        self.Yandex_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Yandex_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Yandex_INF.setObjectName("Yandex_INF")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.Yandex_INF)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.Yandex = QtWidgets.QLabel(self.Yandex_INF)
        self.Yandex.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Yandex.setObjectName("Yandex")
        self.horizontalLayout_24.addWidget(self.Yandex)
        self.C_Yandex = QtWidgets.QLabel(self.Yandex_INF)
        self.C_Yandex.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Yandex.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Yandex.setObjectName("C_Yandex")
        self.horizontalLayout_24.addWidget(self.C_Yandex)
        self.verticalLayout_17.addWidget(self.Yandex_INF)
        self.Tesla_INF = QtWidgets.QFrame(self.group_stocks)
        self.Tesla_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Tesla_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Tesla_INF.setObjectName("Tesla_INF")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.Tesla_INF)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.Tesla = QtWidgets.QLabel(self.Tesla_INF)
        self.Tesla.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Tesla.setObjectName("Tesla")
        self.horizontalLayout_25.addWidget(self.Tesla)
        self.C_Tesla = QtWidgets.QLabel(self.Tesla_INF)
        self.C_Tesla.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Tesla.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Tesla.setObjectName("C_Tesla")
        self.horizontalLayout_25.addWidget(self.C_Tesla)
        self.verticalLayout_17.addWidget(self.Tesla_INF)
        self.Apple_INF = QtWidgets.QFrame(self.group_stocks)
        self.Apple_INF.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Apple_INF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Apple_INF.setObjectName("Apple_INF")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.Apple_INF)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Apple = QtWidgets.QLabel(self.Apple_INF)
        self.Apple.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.Apple.setObjectName("Apple")
        self.horizontalLayout_26.addWidget(self.Apple)
        self.C_Apple = QtWidgets.QLabel(self.Apple_INF)
        self.C_Apple.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"font: 20pt \"Nirmala UI\";")
        self.C_Apple.setAlignment(QtCore.Qt.AlignCenter)
        self.C_Apple.setObjectName("C_Apple")
        self.horizontalLayout_26.addWidget(self.C_Apple)
        self.verticalLayout_17.addWidget(self.Apple_INF)
        self.verticalLayout_18.addWidget(self.group_stocks)
        self.verticalLayout_12.addWidget(self.frame_bg_Stocks)
        self.horizontalLayout_5.addWidget(self.frame_with_value)
        self.frame_left_value = QtWidgets.QFrame(self.frame_scollArea)
        self.frame_left_value.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_left_value.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_left_value.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_value.setObjectName("frame_left_value")
        self.horizontalLayout_5.addWidget(self.frame_left_value)
        self.verticalLayout_11.addWidget(self.frame_scollArea)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.frame_additional_information = QtWidgets.QFrame(self.frame_content_home)
        self.frame_additional_information.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_additional_information.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_additional_information.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"boreder:none;\n"
"border-radius: 10px;\n"
"")
        self.frame_additional_information.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_additional_information.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_additional_information.setObjectName("frame_additional_information")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_additional_information)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(10)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.frame_time = QtWidgets.QFrame(self.frame_additional_information)
        self.frame_time.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_time.setStyleSheet("")
        self.frame_time.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_time.setObjectName("frame_time")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_time)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_TIME = QtWidgets.QLabel(self.frame_time)
        self.label_TIME.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_TIME.setFont(font)
        self.label_TIME.setStyleSheet("color: #FFF;")
        self.label_TIME.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TIME.setObjectName("label_TIME")
        self.verticalLayout_34.addWidget(self.label_TIME)
        self.label_time_inf = QtWidgets.QLabel(self.frame_time)
        self.label_time_inf.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_time_inf.setFont(font)
        self.label_time_inf.setStyleSheet("color: #FFF;")
        self.label_time_inf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_inf.setObjectName("label_time_inf")
        self.verticalLayout_34.addWidget(self.label_time_inf)
        self.verticalLayout_33.addWidget(self.frame_time)
        self.frame_update = QtWidgets.QFrame(self.frame_additional_information)
        self.frame_update.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_update.setFont(font)
        self.frame_update.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_update.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_update.setObjectName("frame_update")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_update)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_UPDATE = QtWidgets.QLabel(self.frame_update)
        self.label_UPDATE.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_UPDATE.setFont(font)
        self.label_UPDATE.setStyleSheet("color: #FFF;")
        self.label_UPDATE.setAlignment(QtCore.Qt.AlignCenter)
        self.label_UPDATE.setObjectName("label_UPDATE")
        self.verticalLayout_35.addWidget(self.label_UPDATE)
        self.label_update_inf = QtWidgets.QLabel(self.frame_update)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_update_inf.setFont(font)
        self.label_update_inf.setStyleSheet("color: #FFF;")
        self.label_update_inf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_update_inf.setObjectName("label_update_inf")
        self.verticalLayout_35.addWidget(self.label_update_inf)
        self.verticalLayout_33.addWidget(self.frame_update)
        self.frame_weather = QtWidgets.QFrame(self.frame_additional_information)
        self.frame_weather.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_weather.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_weather.setObjectName("frame_weather")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_weather)
        self.verticalLayout_36.setContentsMargins(50, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_WEATHER = QtWidgets.QLabel(self.frame_weather)
        self.label_WEATHER.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_WEATHER.setFont(font)
        self.label_WEATHER.setStyleSheet("color: #FFF;\n"
"padding-right: 50px;")
        self.label_WEATHER.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WEATHER.setObjectName("label_WEATHER")
        self.verticalLayout_36.addWidget(self.label_WEATHER)
        self.lineEdit_City = QtWidgets.QLineEdit(self.frame_weather)
        self.lineEdit_City.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lineEdit_City.setFont(font)
        self.lineEdit_City.setStyleSheet("QLineEdit{\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    padding-left:60px;\n"
"}\n"
"\n"
"\n"
"")
        self.lineEdit_City.setText("")
        self.lineEdit_City.setObjectName("lineEdit_City")
        self.verticalLayout_36.addWidget(self.lineEdit_City)
        self.frame_inf_weather = QtWidgets.QFrame(self.frame_weather)
        self.frame_inf_weather.setStyleSheet("padding-right: 50px;")
        self.frame_inf_weather.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_inf_weather.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inf_weather.setObjectName("frame_inf_weather")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_inf_weather)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.frame_temp = QtWidgets.QFrame(self.frame_inf_weather)
        self.frame_temp.setMaximumSize(QtCore.QSize(16777215, 82))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.frame_temp.setFont(font)
        self.frame_temp.setStyleSheet("padding-left: 10px;\n"
"padding-bottom: 10px;")
        self.frame_temp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_temp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_temp.setObjectName("frame_temp")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_temp)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_inf_weater = QtWidgets.QLabel(self.frame_temp)
        self.label_inf_weater.setMinimumSize(QtCore.QSize(85, 0))
        self.label_inf_weater.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_inf_weater.setFont(font)
        self.label_inf_weater.setStyleSheet("color: #FFF;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"padding-right: 20px;")
        self.label_inf_weater.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_inf_weater.setObjectName("label_inf_weater")
        self.horizontalLayout_32.addWidget(self.label_inf_weater)
        self.label_inf_temperature = QtWidgets.QLabel(self.frame_temp)
        self.label_inf_temperature.setMinimumSize(QtCore.QSize(100, 0))
        self.label_inf_temperature.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_inf_temperature.setFont(font)
        self.label_inf_temperature.setStyleSheet("color: #FFF;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"padding-right: -20px;")
        self.label_inf_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inf_temperature.setObjectName("label_inf_temperature")
        self.horizontalLayout_32.addWidget(self.label_inf_temperature)
        self.verticalLayout_37.addWidget(self.frame_temp)
        self.frame_for_btn_weather = QtWidgets.QFrame(self.frame_inf_weather)
        self.frame_for_btn_weather.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_for_btn_weather.setStyleSheet("padding-right: 10px;")
        self.frame_for_btn_weather.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_btn_weather.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_btn_weather.setObjectName("frame_for_btn_weather")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_for_btn_weather)
        self.verticalLayout_38.setContentsMargins(35, 0, 25, 10)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.btn_weather = QtWidgets.QPushButton(self.frame_for_btn_weather)
        self.btn_weather.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_weather.setFont(font)
        self.btn_weather.setStyleSheet("QPushButton {\n"
"    border-radius: 20%;\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    background-color:rgb(44, 44, 44);\n"
"    color: #FFF;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(55, 55, 55);\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(177, 244, 92)\n"
"}\n"
"\n"
"\n"
"")
        self.btn_weather.setObjectName("btn_weather")
        self.verticalLayout_38.addWidget(self.btn_weather)
        self.verticalLayout_37.addWidget(self.frame_for_btn_weather)
        self.verticalLayout_36.addWidget(self.frame_inf_weather)
        self.verticalLayout_33.addWidget(self.frame_weather)
        self.frame_percent = QtWidgets.QFrame(self.frame_additional_information)
        self.frame_percent.setMaximumSize(QtCore.QSize(16777215, 260))
        self.frame_percent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_percent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_percent.setObjectName("frame_percent")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_percent)
        self.verticalLayout_6.setContentsMargins(50, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.frame_percent)
        self.widget.setObjectName("widget")
        self.circular_percentBarBase = QtWidgets.QFrame(self.widget)
        self.circular_percentBarBase.setGeometry(QtCore.QRect(10, 10, 180, 180))
        self.circular_percentBarBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circular_percentBarBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circular_percentBarBase.setObjectName("circular_percentBarBase")
        self.circular_percentProgress = QtWidgets.QFrame(self.circular_percentBarBase)
        self.circular_percentProgress.setGeometry(QtCore.QRect(10, 10, 170, 170))
        self.circular_percentProgress.setStyleSheet("QFrame{\n"
"    border-radius: 80%;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.100 rgba(255, 0, 127, 0), stop:0.100 rgba(120, 230, 130, 255));\n"
"}")
        self.circular_percentProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circular_percentProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circular_percentProgress.setObjectName("circular_percentProgress")
        self.circular_percentBg = QtWidgets.QFrame(self.circular_percentBarBase)
        self.circular_percentBg.setGeometry(QtCore.QRect(10, 10, 170, 170))
        self.circular_percentBg.setStyleSheet("QFrame{\n"
"    border-radius: 80%;\n"
"    background-color: rgba(177, 244, 92, 120);\n"
"}")
        self.circular_percentBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circular_percentBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circular_percentBg.setObjectName("circular_percentBg")
        self.container_percent = QtWidgets.QFrame(self.circular_percentBarBase)
        self.container_percent.setGeometry(QtCore.QRect(15, 15, 160, 160))
        self.container_percent.setStyleSheet("QFrame{\n"
"    border-radius: 75%;\n"
"    background-color: rgb(45, 45, 45);\n"
"}")
        self.container_percent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_percent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_percent.setObjectName("container_percent")
        self.lineEdit_enter_currency_percent = QtWidgets.QLineEdit(self.container_percent)
        self.lineEdit_enter_currency_percent.setGeometry(QtCore.QRect(18, 30, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_enter_currency_percent.setFont(font)
        self.lineEdit_enter_currency_percent.setStyleSheet("QLineEdit{\n"
"    border: rgb(120, 230, 130);\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: #FFF;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(177, 244, 92);    \n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit_enter_currency_percent.setText("")
        self.lineEdit_enter_currency_percent.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_enter_currency_percent.setObjectName("lineEdit_enter_currency_percent")
        self.btn_get_percent = QtWidgets.QPushButton(self.container_percent)
        self.btn_get_percent.setGeometry(QtCore.QRect(50, 110, 60, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.btn_get_percent.setFont(font)
        self.btn_get_percent.setStyleSheet("QPushButton {\n"
"    border-radius: 20%;\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    background-color:rgb(44, 44, 44);\n"
"    color: #FFF\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(55, 55, 55);\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(177, 244, 92)\n"
"}\n"
"\n"
"\n"
"")
        self.btn_get_percent.setObjectName("btn_get_percent")
        self.label_percent_inf = QtWidgets.QLabel(self.container_percent)
        self.label_percent_inf.setGeometry(QtCore.QRect(10, 60, 140, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_percent_inf.setFont(font)
        self.label_percent_inf.setStyleSheet("color: #FFF")
        self.label_percent_inf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percent_inf.setObjectName("label_percent_inf")
        self.circular_percentBg.raise_()
        self.circular_percentProgress.raise_()
        self.container_percent.raise_()
        self.verticalLayout_6.addWidget(self.widget)
        self.verticalLayout_33.addWidget(self.frame_percent)
        self.horizontalLayout_3.addWidget(self.frame_additional_information)
        self.verticalLayout_7.addWidget(self.frame_content_home)
        self.stackedWidget.addWidget(self.page_Home)
        self.page_Converter = QtWidgets.QWidget()
        self.page_Converter.setObjectName("page_Converter")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_Converter)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_main_converter = QtWidgets.QFrame(self.page_Converter)
        self.frame_main_converter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main_converter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_converter.setObjectName("frame_main_converter")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_main_converter)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.frame_converter_left = QtWidgets.QFrame(self.frame_main_converter)
        self.frame_converter_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_converter_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_converter_left.setObjectName("frame_converter_left")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_converter_left)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.groupBox_converter = QtWidgets.QGroupBox(self.frame_converter_left)
        self.groupBox_converter.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.groupBox_converter.setFont(font)
        self.groupBox_converter.setStyleSheet("QGroupBox {\n"
"    border-radius: 30px;\n"
"    color: rgb(120, 230, 130);\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"}\n"
"")
        self.groupBox_converter.setObjectName("groupBox_converter")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.groupBox_converter)
        self.horizontalLayout_31.setContentsMargins(9, 40, 9, 9)
        self.horizontalLayout_31.setSpacing(6)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.frame_converter_left_inf = QtWidgets.QFrame(self.groupBox_converter)
        self.frame_converter_left_inf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_converter_left_inf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_converter_left_inf.setObjectName("frame_converter_left_inf")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_converter_left_inf)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_converter_inf = QtWidgets.QFrame(self.frame_converter_left_inf)
        self.frame_converter_inf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_converter_inf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_converter_inf.setObjectName("frame_converter_inf")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_converter_inf)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.lineEdit_from_the_currency = QtWidgets.QLineEdit(self.frame_converter_inf)
        self.lineEdit_from_the_currency.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.lineEdit_from_the_currency.setFont(font)
        self.lineEdit_from_the_currency.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    border-radius: 20%;\n"
"    color: #FFF;\n"
"    background-color:rgb(44, 44, 44);\n"
"    padding-left: 15px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"    background-color:rgb(68, 68, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.lineEdit_from_the_currency.setText("")
        self.lineEdit_from_the_currency.setObjectName("lineEdit_from_the_currency")
        self.verticalLayout_30.addWidget(self.lineEdit_from_the_currency)
        self.lineEdit_the_amount = QtWidgets.QLineEdit(self.frame_converter_inf)
        self.lineEdit_the_amount.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.lineEdit_the_amount.setFont(font)
        self.lineEdit_the_amount.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    border-radius: 20%;\n"
"    color: #FFF;\n"
"    background-color:rgb(44, 44, 44);\n"
"    padding-left: 15px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"    background-color:rgb(68, 68, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.lineEdit_the_amount.setText("")
        self.lineEdit_the_amount.setObjectName("lineEdit_the_amount")
        self.verticalLayout_30.addWidget(self.lineEdit_the_amount)
        self.lineEdit_to_the_currency = QtWidgets.QLineEdit(self.frame_converter_inf)
        self.lineEdit_to_the_currency.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.lineEdit_to_the_currency.setFont(font)
        self.lineEdit_to_the_currency.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    border-radius: 20%;\n"
"    color: #FFF;\n"
"    background-color:rgb(44, 44, 44);\n"
"    padding-left: 15px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"    background-color:rgb(68, 68, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.lineEdit_to_the_currency.setText("")
        self.lineEdit_to_the_currency.setObjectName("lineEdit_to_the_currency")
        self.verticalLayout_30.addWidget(self.lineEdit_to_the_currency)
        self.label_converter_get_it = QtWidgets.QLabel(self.frame_converter_inf)
        self.label_converter_get_it.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.label_converter_get_it.setFont(font)
        self.label_converter_get_it.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    border-radius: 20%;\n"
"    color: #FFF;\n"
"    background-color:rgb(44, 44, 44);\n"
"    padding-left: 15px;\n"
"}\n"
"QLabel:hover {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"}\n"
"QLabel:focus {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"    background-color:rgb(68, 68, 68);\n"
"}\n"
"\n"
"\n"
"")
        self.label_converter_get_it.setObjectName("label_converter_get_it")
        self.verticalLayout_30.addWidget(self.label_converter_get_it)
        self.verticalLayout_29.addWidget(self.frame_converter_inf)
        self.frame_converter_button = QtWidgets.QFrame(self.frame_converter_left_inf)
        self.frame_converter_button.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_converter_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_converter_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_converter_button.setObjectName("frame_converter_button")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_converter_button)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.btn_converter = QtWidgets.QPushButton(self.frame_converter_button)
        self.btn_converter.setMinimumSize(QtCore.QSize(300, 60))
        self.btn_converter.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.btn_converter.setFont(font)
        self.btn_converter.setStyleSheet("QPushButton {\n"
"    border-radius: 20%;\n"
"    border: 2px solid rgb(120, 230, 130);\n"
"    background-color:rgb(44, 44, 44);\n"
"    color: #FFF\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(177, 244, 92);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 230, 130);\n"
"}\n"
"")
        self.btn_converter.setObjectName("btn_converter")
        self.verticalLayout_31.addWidget(self.btn_converter)
        self.verticalLayout_29.addWidget(self.frame_converter_button)
        self.horizontalLayout_31.addWidget(self.frame_converter_left_inf)
        self.frame_converter_right_inf = QtWidgets.QFrame(self.groupBox_converter)
        self.frame_converter_right_inf.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_converter_right_inf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_converter_right_inf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_converter_right_inf.setObjectName("frame_converter_right_inf")
        self.horizontalLayout_31.addWidget(self.frame_converter_right_inf)
        self.verticalLayout_28.addWidget(self.groupBox_converter)
        self.horizontalLayout_30.addWidget(self.frame_converter_left)
        self.frame_converter_right = QtWidgets.QFrame(self.frame_main_converter)
        self.frame_converter_right.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_converter_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_converter_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_converter_right.setObjectName("frame_converter_right")
        self.horizontalLayout_30.addWidget(self.frame_converter_right)
        self.verticalLayout_9.addWidget(self.frame_main_converter)
        self.frame_converter_bottom = QtWidgets.QFrame(self.page_Converter)
        self.frame_converter_bottom.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_converter_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_converter_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_converter_bottom.setObjectName("frame_converter_bottom")
        self.verticalLayout_9.addWidget(self.frame_converter_bottom)
        self.stackedWidget.addWidget(self.page_Converter)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Home.setText(_translate("MainWindow", "       Home"))
        self.btn_Converter.setText(_translate("MainWindow", "        Converter"))
        self.btn_Excel.setText(_translate("MainWindow", "         Excel"))
        self.label_TO_THE_RUB.setText(_translate("MainWindow", "To the RUB"))
        self.group_currencies.setTitle(_translate("MainWindow", "Currencies"))
        self.USD.setText(_translate("MainWindow", "USD"))
        self.C_USD.setText(_translate("MainWindow", "123456,78$"))
        self.EUR.setText(_translate("MainWindow", "EUR"))
        self.C_EUR.setText(_translate("MainWindow", "123456,78$"))
        self.GBP.setText(_translate("MainWindow", "GBP"))
        self.C_GBP.setText(_translate("MainWindow", "123456,78$"))
        self.TRY.setText(_translate("MainWindow", "TRY"))
        self.C_TRY.setText(_translate("MainWindow", "123456,78$"))
        self.JPY.setText(_translate("MainWindow", "JPY"))
        self.C_JPY.setText(_translate("MainWindow", "123456,78$"))
        self.AUD.setText(_translate("MainWindow", "AUD"))
        self.C_AUD.setText(_translate("MainWindow", "123456,78$"))
        self.BTC.setText(_translate("MainWindow", "BTC"))
        self.C_BTC.setText(_translate("MainWindow", "123456,78$"))
        self.ETH.setText(_translate("MainWindow", "ETH"))
        self.C_ETH.setText(_translate("MainWindow", "123456,78$"))
        self.group_products.setTitle(_translate("MainWindow", "Products"))
        self.OilBrent.setText(_translate("MainWindow", "OilBrent"))
        self.C_OilBrent.setText(_translate("MainWindow", "123456,78$"))
        self.OilWTI.setText(_translate("MainWindow", "OilWTI"))
        self.C_OilWTI.setText(_translate("MainWindow", "123456,78$"))
        self.Gold.setText(_translate("MainWindow", "Gold"))
        self.C_Gold.setText(_translate("MainWindow", "123456,78$"))
        self.Silver.setText(_translate("MainWindow", "Silver"))
        self.C_Silver.setText(_translate("MainWindow", "123456,78$"))
        self.Platinum.setText(_translate("MainWindow", "Platinum"))
        self.C_Platinum.setText(_translate("MainWindow", "123456,78$"))
        self.Palladium.setText(_translate("MainWindow", "Palladium"))
        self.C_Palladium.setText(_translate("MainWindow", "123456,78$"))
        self.Gas.setText(_translate("MainWindow", "Gas"))
        self.C_Gas.setText(_translate("MainWindow", "123456,78$"))
        self.group_stocks.setTitle(_translate("MainWindow", "Products"))
        self.Sberbank.setText(_translate("MainWindow", "Sberbank"))
        self.C_Sberbank.setText(_translate("MainWindow", "123456,78$"))
        self.Gazprom.setText(_translate("MainWindow", "Gazprom"))
        self.C_Gazprom.setText(_translate("MainWindow", "123456,78$"))
        self.Lukoil.setText(_translate("MainWindow", "Lukoil"))
        self.C_Lukoil.setText(_translate("MainWindow", "123456,78$"))
        self.Yandex.setText(_translate("MainWindow", "Yandex"))
        self.C_Yandex.setText(_translate("MainWindow", "123456,78$"))
        self.Tesla.setText(_translate("MainWindow", "Tesla"))
        self.C_Tesla.setText(_translate("MainWindow", "123456,78$"))
        self.Apple.setText(_translate("MainWindow", "Apple"))
        self.C_Apple.setText(_translate("MainWindow", "123456,78$"))
        self.label_TIME.setText(_translate("MainWindow", "TIME"))
        self.label_time_inf.setText(_translate("MainWindow", "16:00"))
        self.label_UPDATE.setText(_translate("MainWindow", "UPDATE"))
        self.label_update_inf.setText(_translate("MainWindow", "00:00"))
        self.label_WEATHER.setText(_translate("MainWindow", "WEATHER"))
        self.lineEdit_City.setPlaceholderText(_translate("MainWindow", "   City"))
        self.label_inf_weater.setText(_translate("MainWindow", "\n"
"C° \n"
" F°"))
        self.label_inf_temperature.setText(_translate("MainWindow", "\n"
"-\n"
"-"))
        self.btn_weather.setText(_translate("MainWindow", "Get"))
        self.lineEdit_enter_currency_percent.setPlaceholderText(_translate("MainWindow", "CURRENCY"))
        self.btn_get_percent.setText(_translate("MainWindow", "Get"))
        self.label_percent_inf.setText(_translate("MainWindow", "0,00%"))
        self.groupBox_converter.setTitle(_translate("MainWindow", "Converter"))
        self.lineEdit_from_the_currency.setPlaceholderText(_translate("MainWindow", "From The currency"))
        self.lineEdit_the_amount.setPlaceholderText(_translate("MainWindow", "The Amount"))
        self.lineEdit_to_the_currency.setPlaceholderText(_translate("MainWindow", "To the currency"))
        self.label_converter_get_it.setText(_translate("MainWindow", "I\'ll get it"))
        self.btn_converter.setText(_translate("MainWindow", "Get"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
